### PR TITLE
Experimentation with web keyboard

### PR DESCRIPTION
**Pull request by PeterJensen**
Hi, I'm opening this PR as a place to discuss a touch device keyboard solution.

As an experiment, I tried to do a web-based keyboard layout that looks like the real thing (based on this picture)

image

When choosing the iPhone in Chrome dev tools it looks like this:
image

Maybe you can give it a try on a real iPhone: https://peterjensen.github.io/virtual-nascom/n2-kbd.html

Not sure if the buttons are too small to be useful on a real iPhone display.

### CODE REVIEW

**Comment by tommythorn** [comment]
I hate to be a downer, but I went that route already in jsnascom and my conclusion was that it was a total failure.  When used in portrait mode (which is by far the most common and required to get enough vertical screen space, the keyboard becomes way too small if it has to fit everything.

Also, I did go for a the dual mode in virtual nascom ("raw" and "natural") to support applications/games that use the keys more as controllers, but in retrospect, "raw" has very limited usefulness and especially for the web, this is a non-starter IMO.

I'd encourage you to experiment with it and gain experience.  In my opinion it's too painful to use.  What I've been looking into is a tricky similar to, say, https://xtermjs.org/ which (if I understand correctly) uses an invisible text field under the display to prompt the mobile keyboard.

ADD: it's a beautiful keyboard though!  Much nicer than what I produced.

**Comment by tommythorn** [comment]
PS: Your design is beautiful though!  Much nicer than what I produced.

I also would like to add sliding motions on the text display to be interpreted as cursor moments (as it done by eg. Terminus and others), but I don't know how to produce the shifted versions of the cursor keys that I so important on Nascom.

**Comment by tommythorn** [comment]
Some interesting ideas: https://github.com/xtermjs/xterm.js/issues/1101 (and see https://github.com/ajaxorg/ace/blob/eb2437badf4013893e15cb873057607c09cc95ae/lib/ace/keyboard/textinput_ios.js#L483-L526)

**Comment by PeterJensen** [comment]
Yeah, I think I've reached the same conclusion.  I used this mainly as a challenge to myself to see what was possible with some of the new CSS features (flex-box).  I used to do a fair amount of web development, but hasn't for a while, so it was good to re-familiarize myself with the state of affairs.

**Comment by tommythorn** [comment]
Your work on this is deeply appreciated and I don't want to discourage you.  As far as I can tell you have a better understanding of web standards than me and would likely do a better job.  I'm still trying to understand how xterm.js pulls off the "hidden input field" trick to pop up a mobile keyboard.

**Comment by PeterJensen** [comment]
I found a stackoverflow article talking about this:
   https://stackoverflow.com/questions/12204571/mobile-safari-javascript-focus-method-on-inputfield-only-works-with-click

I tried to do what it says, but on Android it doesn't work.  Not sure about iOS.  Maybe you can give it try here:
   https://peterjensen.github.io/virtual-nascom/kbd-use.html

**Comment by tommythorn** [comment]
Hmm, didn't work for me; I see a white page with the "Page with keyboard" headline no matter where I tap.  No keyboard.

FWIW, xtermjs.org works and pops up a keyboard once I tap in the big black area:
IMG_4705

**Comment by PeterJensen** [comment]
The intent was to have the keyboard be there without having to tap anywhere.  That's what you're after, right?  I wasn't very confident that it would work :)  Oh well, I'll 'noodle' on it a bit more. (MQ reference :)

**Comment by tommythorn** [comment]
I have no idea if it's possible to do without tapping once, but I don't so much care about tapping once.  I do prefer not having to have a visible dummy input field, but that method works, as illustrated by https://tommythorn.github.io/jsnascom/index.html
UNADJUSTEDNONRAW_thumb_2a77
 
Note, that page has a lot of issue, eg. backspace on the keyboard isn't registered as a keypress.  I imagine most of these are solvable.

**Comment by tommythorn** [comment]
Try https://tommythorn.github.io/virtual-nascom/mobile.html on your phone.  I've temporarily taken over Reset to bring up a keyboard.  It works on iOS at least (but some keys, like '(' and ')', are entered incorrectly 👎  which looks like an Emscripten bug, sigh).

**Comment by PeterJensen** [comment]
Pushing reset on Android didn't bring up the keyboard :(

I was experimenting with a 'hidden input field' to bring up the keyboard.  On this page:

  https://peterjensen.github.io/virtual-nascom/kbd-use.html

The keyboard does come up on Android when clicking on the canvas, but the keydown event doesn't seem to be captured.
Can you try it on iOS/Safari?

BTW: I think the keypress event has been deprecated in favor of keydown and keyup.  Also the keyCode property of the event seems to be deprecated, in favor of .code

**Comment by tommythorn** [comment]
works perfectly - keyboard is brought up on tap on the black canvas and key events are shown there. Alas, ()$& all result in digits instead of the actual key:

**Comment by PeterJensen** [comment]
It turned out you couldn't change the focus to an element that were truly hidden.  Instead I wrapped it in a
`<div style="width:0; height:0; overflow:hidden">...</div>`
Too bad the keydown event doesn't fire with the Android built-in keyboard

EDIT: Evidently, others have this problem too: https://bugs.chromium.org/p/chromium/issues/detail?id=118639

There's suggestions to install third-party keyboards.  That seems like too much trouble, IMO

**Comment by tommythorn** [comment]
Filed https://github.com/emscripten-core/emscripten/issues/15285 on the 15 broken keys.

**Comment by tommythorn** [comment]
@PeterJensen does the Android mobile keyboard work for you on http://xtermjs.org ?  If so, there must be a solution.

**Comment by PeterJensen** [comment]
@tommythorn Yes, the xtermjs.org worked on the Chrome Android browser!

I looked at how they did it.  Turns out that the 'keydown' event is triggered for every keypress on the Android keyboard, however, the keyCode is reported as 229 regardless of which key is pressed.  They get around this by fetching the last character of the hidden textarea.  However, they have to wait until it's actually there, which they do by scheduling a timeout handler to do that.

The code in xtermjs that's doing this is here:

https://github.com/xtermjs/xterm.js/blob/a9788c364dc267ef8959cf75ed5d008e34f38616/src/browser/input/CompositionHelper.ts#L108-L113

and

https://github.com/xtermjs/xterm.js/blob/a9788c364dc267ef8959cf75ed5d008e34f38616/src/browser/input/CompositionHelper.ts#L183-L196

I've mimicked the same technique in my little test program, and it seems to work in Android.  Can you check if it still works with iOS Safari?

https://peterjensen.github.io/virtual-nascom/kbd-use.html

**Comment by tommythorn** [comment]
ding ding ding we have a winner.  Honestly that sounds crazy complicated but it looks like you got it.  Even the keys that are broken in emscripten SDL appear to work.

**Comment by PeterJensen** [comment]
I made some changes to virtual-nascom.html:
- Made the canvas bigger for desktop browsers
- Made it scale properly for mobile to take up all horizontal space
- Added a 'Keyboard' button to bring up the keyboard on mobile
I haven't incorporated the keydown hack for Android yet to pass the keystrokes, but I think it should work for iOS.
Do you mind giving it a try?
https://peterjensen.github.io/virtual-nascom/virtual-nascom.html
I'll submit a proper PR for it, if you're OK with it.

**Comment by tommythorn** [comment]
Thanks. Scaling was good on Mobile, but had artifacts on desktop:
Screen Shot 2021-10-18 at 09 29 44

Keyboard comes up when hitting "Keyboard" but of course it has the SDL keyboard problem where 15 (rather important) keys don't work so it's not particularly usable.

However it's converging to a good place.  Once the keyboard is solved, I think persistent state (via LocalState) and load/store from tape are the only remaining issues.

**Comment by PeterJensen** [comment]
Damn!  I thought I had it figured out.  I seem to get the extra horizontal line of white pixels right around the middle of the screen.  Is that where you see it too?

**Comment by tommythorn** [comment]
I think this is stale now that #15 went in.  Do you want to keep it open?

**Comment by PeterJensen** [comment]
No.  It can be closed.

**Pull request closed without merging**
